/**
 * M4 Replacement Effect Interceptor — Pipeline Step 3
 *
 * Scans active replacement effects and substitutes actions before execution.
 * Implements rules §6-6-3: "instead of X, do Y".
 *
 * Key rules:
 * - A replacement effect can only apply once per original event (§6-6-3-5)
 * - If multiple replacements match, the affected player chooses which applies
 * - Replacement effects are consumed (removed) once they apply (if one-time)
 */

import type {
  RuntimeActiveEffect,
} from "./effect-types.js";
import type { CardData, GameAction, GameState, PendingEvent } from "../types.js";

export interface ReplacementResult {
  replaced: boolean;
  state: GameState;
  /** If replaced, the substitute action to execute instead */
  substituteAction?: GameAction;
  /** Events generated by the replacement itself */
  events: PendingEvent[];
}

/**
 * Check for replacement effects that intercept an action.
 *
 * Currently supports:
 * - KO → RETURN_TO_HAND (e.g., "When this Character would be KO'd, return it to hand instead")
 * - KO → BOTTOM_OF_DECK
 * - DAMAGE → PREVENT (e.g., "The next time this Leader would take damage, prevent it")
 */
export function checkReplacements(
  state: GameState,
  action: GameAction,
  cardDb: Map<string, CardData>,
  actingPlayerIndex: 0 | 1,
): ReplacementResult {
  const effects = state.activeEffects as RuntimeActiveEffect[];
  const replacements = effects.filter((e) =>
    e.modifiers?.some((m) => m.type === "REPLACEMENT_EFFECT"),
  );

  if (replacements.length === 0) {
    return { replaced: false, state, events: [] };
  }

  // Check each replacement effect against the action
  for (const replacement of replacements) {
    const mod = replacement.modifiers?.find((m) => m.type === "REPLACEMENT_EFFECT");
    if (!mod) continue;

    const result = tryReplace(state, action, replacement, mod.params ?? {}, cardDb, actingPlayerIndex);
    if (result) {
      return result;
    }
  }

  return { replaced: false, state, events: [] };
}

function tryReplace(
  _state: GameState,
  _action: GameAction,
  _effect: RuntimeActiveEffect,
  params: Record<string, unknown>,
  _cardDb: Map<string, CardData>,
  _actingPlayerIndex: 0 | 1,
): ReplacementResult | null {
  const trigger = (params.trigger as string) ?? "";

  // KO replacement
  if (trigger === "KO" || trigger === "WOULD_BE_KO") {
    // This intercepts at the engine level — KO events check
    // active replacements before completing
    // For action-level, we don't intercept DECLARE_ATTACK etc.
    // KO replacements are checked in the effect resolver's koCharacter
    return null;
  }

  // Damage replacement
  if (trigger === "DAMAGE" || trigger === "WOULD_TAKE_DAMAGE") {
    // Also checked at the battle damage step level
    return null;
  }

  return null;
}

/**
 * Check if a specific KO would be replaced.
 * Called by the effect resolver and battle system before completing a KO.
 */
export function checkKOReplacement(
  state: GameState,
  targetInstanceId: string,
  _cardDb: Map<string, CardData>,
): { replaced: boolean; state: GameState; events: PendingEvent[] } {
  const effects = state.activeEffects as RuntimeActiveEffect[];

  for (const effect of effects) {
    const mod = effect.modifiers?.find((m) => m.type === "REPLACEMENT_EFFECT");
    if (!mod) continue;

    const trigger = (mod.params?.trigger as string) ?? "";
    if (trigger !== "KO" && trigger !== "WOULD_BE_KO") continue;

    // Check if this replacement applies to the target
    if (effect.appliesTo && effect.appliesTo.length > 0) {
      if (!effect.appliesTo.includes(targetInstanceId)) continue;
    }

    const replacement = (mod.params?.replacement as string) ?? "";
    const events: PendingEvent[] = [];

    if (replacement === "RETURN_TO_HAND") {
      // Instead of KO, return to hand
      let nextState = returnToHandInstead(state, targetInstanceId);
      if (nextState) {
        // Remove the one-time replacement effect
        nextState = removeActiveEffect(nextState, effect.id);
        events.push({
          type: "CARD_RETURNED_TO_HAND",
          payload: { cardInstanceId: targetInstanceId, replacedKO: true },
        });
        return { replaced: true, state: nextState, events };
      }
    }

    if (replacement === "BOTTOM_OF_DECK") {
      let nextState = returnToDeckInstead(state, targetInstanceId, "BOTTOM");
      if (nextState) {
        nextState = removeActiveEffect(nextState, effect.id);
        return { replaced: true, state: nextState, events };
      }
    }

    if (replacement === "PREVENT") {
      // Simply prevent the KO
      let nextState = removeActiveEffect(state, effect.id);
      return { replaced: true, state: nextState, events };
    }
  }

  return { replaced: false, state, events: [] };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function removeActiveEffect(state: GameState, effectId: string): GameState {
  const effects = (state.activeEffects as RuntimeActiveEffect[]).filter(
    (e) => e.id !== effectId,
  );
  return { ...state, activeEffects: effects as any };
}

function returnToHandInstead(state: GameState, instanceId: string): GameState | null {
  for (const [pi, player] of state.players.entries()) {
    const charIdx = player.characters.findIndex((c) => c.instanceId === instanceId);
    if (charIdx === -1) continue;

    const char = player.characters[charIdx];
    const newChars = player.characters.filter((_, i) => i !== charIdx);

    const returnedDon = char.attachedDon.map((d) => ({
      ...d,
      state: "RESTED" as const,
      attachedTo: null,
    }));

    const newHand = [
      ...player.hand,
      { ...char, zone: "HAND" as const, attachedDon: [], state: "ACTIVE" as const },
    ];

    const newPlayers = [...state.players] as [typeof state.players[0], typeof state.players[1]];
    newPlayers[pi] = {
      ...player,
      characters: newChars,
      hand: newHand,
      donCostArea: [...player.donCostArea, ...returnedDon],
    };

    return { ...state, players: newPlayers };
  }
  return null;
}

function returnToDeckInstead(
  state: GameState,
  instanceId: string,
  position: "TOP" | "BOTTOM",
): GameState | null {
  for (const [pi, player] of state.players.entries()) {
    const charIdx = player.characters.findIndex((c) => c.instanceId === instanceId);
    if (charIdx === -1) continue;

    const char = player.characters[charIdx];
    const newChars = player.characters.filter((_, i) => i !== charIdx);

    const returnedDon = char.attachedDon.map((d) => ({
      ...d,
      state: "RESTED" as const,
      attachedTo: null,
    }));

    const deckCard = { ...char, zone: "DECK" as const, attachedDon: [], state: "ACTIVE" as const };
    const newDeck = position === "BOTTOM"
      ? [...player.deck, deckCard]
      : [deckCard, ...player.deck];

    const newPlayers = [...state.players] as [typeof state.players[0], typeof state.players[1]];
    newPlayers[pi] = {
      ...player,
      characters: newChars,
      deck: newDeck,
      donCostArea: [...player.donCostArea, ...returnedDon],
    };

    return { ...state, players: newPlayers };
  }
  return null;
}
