import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { collectExportedSchemas } from "../src/engine/schema-source-parity.js";
import type { EffectSchema } from "../src/engine/effect-types.js";

const workerRoot = resolve(process.cwd());
const schemasDirectory = resolve(workerRoot, "src/engine/schemas");
const outputPath = resolve(
  workerRoot,
  "src/engine/authored-schemas.generated.ts"
);
const schemaSourcePattern = /^(?:(?:op|eb|st|prb)\d+|p)\.ts$/;

async function buildRegistry(): Promise<Record<string, EffectSchema>> {
  const registry: Record<string, EffectSchema> = {};
  const sources = new Map<string, string>();
  const files = readdirSync(schemasDirectory)
    .filter((file) => schemaSourcePattern.test(file))
    .sort();

  for (const file of files) {
    const exports = await import(
      pathToFileURL(resolve(schemasDirectory, file)).href
    );
    const schemas = collectExportedSchemas(exports);
    if (Object.keys(schemas).length === 0) {
      throw new Error(`${file} exports no EffectSchema objects`);
    }
    for (const [cardId, schema] of Object.entries(schemas)) {
      const previous = sources.get(cardId);
      if (previous) {
        throw new Error(
          `${cardId} is exported by both ${previous} and ${file}`
        );
      }
      sources.set(cardId, file);
      registry[cardId] = schema;
    }
  }

  return Object.fromEntries(
    Object.entries(registry).sort(([left], [right]) =>
      left.localeCompare(right)
    )
  );
}

function render(registry: Record<string, EffectSchema>): string {
  return (
    `// Generated by scripts/generate-schema-registry.ts. Do not edit.\n` +
    `import type { EffectSchema } from "./effect-types.js";\n\n` +
    `export const AUTHORED_SCHEMAS: Record<string, EffectSchema> = ${JSON.stringify(registry)};\n`
  );
}

async function main(): Promise<void> {
  const rendered = render(await buildRegistry());
  if (process.argv.includes("--check")) {
    const current = readFileSync(outputPath, "utf8");
    if (current !== rendered) {
      console.error(
        "Generated schema registry is stale. Run pnpm schema:generate."
      );
      process.exitCode = 1;
    } else {
      console.log("Generated schema registry is current.");
    }
  } else {
    writeFileSync(outputPath, rendered);
    console.log(`Generated ${outputPath}.`);
  }
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
