type FacetValue = readonly [value: string, label: string];

function facetTags<
  const Group extends string,
  const Values extends readonly FacetValue[],
>(
  group: Group,
  values: Values
): {
  [Index in keyof Values]: Values[Index] extends FacetValue
    ? { id: `${Group}:${Values[Index][0]}`; label: Values[Index][1] }
    : never;
} {
  return values.map(([value, label]) => ({
    id: `${group}:${value}`,
    label,
  })) as {
    [Index in keyof Values]: Values[Index] extends FacetValue
      ? { id: `${Group}:${Values[Index][0]}`; label: Values[Index][1] }
      : never;
  };
}

/**
 * Ordered Tier 1 effect-facet vocabulary shared by pipeline and app code.
 * Keep additions synchronized with docs/cards/EFFECT-FACET-TAXONOMY.md.
 */
export const EFFECT_FACET_GROUPS = [
  {
    id: "trigger",
    label: "Trigger",
    tags: facetTags("trigger", [
      ["on_play", "On Play"],
      ["when_attacking", "When Attacking"],
      ["when_attacked", "When Attacked"],
      ["on_ko", "On K.O."],
      ["on_block", "On Block"],
      ["on_opponent_attack", "On Opponent Attack"],
      ["activate_main", "Activate: Main"],
      ["main_event", "Main Event"],
      ["counter", "Counter"],
      ["counter_event", "Counter Event"],
      ["trigger", "Trigger"],
      ["end_of_your_turn", "End of Your Turn"],
      ["end_of_opponent_turn", "End of Opponent Turn"],
      ["start_of_turn", "Start of Turn"],
      ["opponent_character_ko", "Opponent Character K.O."],
      ["any_character_ko", "Any Character K.O."],
      ["any_character_trashed", "Any Character Trashed"],
      ["opponent_character_trashed", "Opponent Character Trashed"],
      ["character_removed_from_field", "Character Removed from Field"],
      ["don_returned_to_don_deck", "DON!! Returned to DON!! Deck"],
      ["don_given_to_card", "DON!! Given to Card"],
      ["event_activated_from_hand", "Event Activated from Hand"],
      ["event_main_resolved_from_trash", "Event Main Resolved from Trash"],
      ["event_trigger_resolved", "Event Trigger Resolved"],
      ["character_played", "Character Played"],
      ["card_removed_from_life", "Card Removed from Life"],
      ["life_card_removed", "Life Card Removed"],
      ["trigger_activated", "Trigger Activated"],
      ["combat_victory", "Combat Victory"],
      ["character_battles", "Character Battles"],
      ["end_of_battle", "End of Battle"],
      ["battle_aborted", "Battle Aborted"],
      ["life_count_becomes_zero", "Life Count Becomes Zero"],
      ["card_added_to_hand_from_life", "Card Added to Hand from Life"],
      ["draw_outside_draw_phase", "Draw Outside Draw Phase"],
      ["character_becomes_rested", "Character Becomes Rested"],
      ["character_returned_to_hand", "Character Returned to Hand"],
      ["damage_taken", "Damage Taken"],
      ["blocker_activated", "Blocker Activated"],
      ["leader_attack_deals_damage", "Leader Attack Deals Damage"],
    ]),
  },
  {
    id: "timing",
    label: "Timing",
    tags: facetTags("timing", [
      ["don_requirement", "DON!! Requirement"],
      ["your_turn", "Your Turn"],
      ["opponent_turn", "Opponent Turn"],
    ]),
  },
  {
    id: "category",
    label: "Category",
    tags: facetTags("category", [
      ["auto", "Auto"],
      ["activate", "Activate"],
      ["permanent", "Permanent"],
      ["replacement", "Replacement"],
      ["rule_modification", "Rule Modification"],
    ]),
  },
  {
    id: "keyword",
    label: "Keyword",
    tags: facetTags("keyword", [
      ["rush", "Rush"],
      ["blocker", "Blocker"],
      ["double_attack", "Double Attack"],
      ["banish", "Banish"],
      ["unblockable", "Unblockable"],
      ["rush_character", "Rush: Character"],
      ["can_attack_active", "Can Attack Active"],
      ["rush:granted", "Rush (Granted)"],
      ["blocker:granted", "Blocker (Granted)"],
      ["double_attack:granted", "Double Attack (Granted)"],
      ["banish:granted", "Banish (Granted)"],
      ["unblockable:granted", "Unblockable (Granted)"],
      ["rush_character:granted", "Rush: Character (Granted)"],
      ["can_attack_active:granted", "Can Attack Active (Granted)"],
    ]),
  },
  {
    id: "removal",
    label: "Removal",
    tags: facetTags("removal", [
      ["ko", "K.O."],
      ["ko:wipe", "K.O. Wipe"],
      ["trash", "Trash"],
      ["trash:wipe", "Trash Wipe"],
      ["bounce", "Return to Hand"],
      ["bounce:wipe", "Return to Hand Wipe"],
      ["bottom_deck", "Bottom Deck"],
      ["bottom_deck:wipe", "Bottom Deck Wipe"],
      ["top_deck", "Top Deck"],
      ["top_deck:wipe", "Top Deck Wipe"],
    ]),
  },
  {
    id: "don",
    label: "DON!!",
    tags: facetTags("don", [
      ["ramp", "Ramp"],
      ["ramp:self", "Ramp — Self"],
      ["ramp:opponent", "Ramp — Opponent"],
      ["untap", "Untap"],
      ["untap:self", "Untap — Self"],
      ["untap:opponent", "Untap — Opponent"],
      ["give", "Give"],
      ["give:self", "Give — Self"],
      ["give:opponent", "Give — Opponent"],
      ["return", "Return"],
      ["return:self", "Return — Self"],
      ["return:opponent", "Return — Opponent"],
      ["rest", "Rest"],
      ["rest:self", "Rest — Self"],
      ["rest:opponent", "Rest — Opponent"],
    ]),
  },
  {
    id: "life",
    label: "Life",
    tags: facetTags("life", [
      ["add", "Add"],
      ["add:self", "Add — Self"],
      ["add:opponent", "Add — Opponent"],
      ["trash", "Trash"],
      ["trash:self", "Trash — Self"],
      ["trash:opponent", "Trash — Opponent"],
      ["to_hand", "To Hand"],
      ["to_hand:self", "To Hand — Self"],
      ["to_hand:opponent", "To Hand — Opponent"],
      ["to_deck", "To Deck"],
      ["to_deck:self", "To Deck — Self"],
      ["to_deck:opponent", "To Deck — Opponent"],
      ["face_up", "Turn Face Up"],
      ["face_up:self", "Turn Face Up — Self"],
      ["face_up:opponent", "Turn Face Up — Opponent"],
      ["face_down", "Turn Face Down"],
      ["face_down:self", "Turn Face Down — Self"],
      ["face_down:opponent", "Turn Face Down — Opponent"],
      ["scry", "Scry"],
      ["scry:self", "Scry — Self"],
      ["scry:opponent", "Scry — Opponent"],
      ["damage", "Damage"],
      ["damage:self", "Damage — Self"],
      ["damage:opponent", "Damage — Opponent"],
      ["drain", "Drain"],
      ["drain:self", "Drain — Self"],
      ["drain:opponent", "Drain — Opponent"],
    ]),
  },
  {
    id: "state",
    label: "State",
    tags: facetTags("state", [
      ["rest", "Rest"],
      ["rest:self", "Rest — Self"],
      ["rest:opponent", "Rest — Opponent"],
      ["active", "Set Active"],
      ["active:self", "Set Active — Self"],
      ["active:opponent", "Set Active — Opponent"],
      ["prohibit", "Prohibit"],
      ["negate", "Negate"],
      ["redirect", "Redirect"],
    ]),
  },
  {
    id: "hand",
    label: "Hand and Deck",
    tags: facetTags("hand", [
      ["draw", "Draw"],
      ["search", "Search Deck"],
      ["search_trash", "Search Trash"],
      ["scry", "Scry Deck"],
      ["mill", "Mill"],
      ["reveal", "Reveal"],
      ["discard", "Discard"],
      ["to_deck", "Hand to Deck"],
      ["wheel", "Wheel"],
      ["event_reuse", "Reuse Event"],
      ["grant_counter", "Grant Counter"],
      ["play_from_hand", "Play from Hand"],
      ["play_from_trash", "Play from Trash"],
      ["play_from_deck", "Play from Deck"],
      ["play_from_life", "Play from Life"],
    ]),
  },
  {
    id: "stat",
    label: "Stats",
    tags: facetTags("stat", [
      ["power_up", "Power Up"],
      ["power_up:self", "Power Up — Self"],
      ["power_up:opponent", "Power Up — Opponent"],
      ["power_down", "Power Down"],
      ["power_down:self", "Power Down — Self"],
      ["power_down:opponent", "Power Down — Opponent"],
      ["cost_up", "Cost Up"],
      ["cost_up:self", "Cost Up — Self"],
      ["cost_up:opponent", "Cost Up — Opponent"],
      ["cost_down", "Cost Down"],
      ["cost_down:self", "Cost Down — Self"],
      ["cost_down:opponent", "Cost Down — Opponent"],
      ["power_to_zero", "Power to Zero"],
      ["set_base_power", "Set Base Power"],
      ["set_cost", "Set Cost"],
      ["copy_power", "Copy Power"],
      ["swap_base_power", "Swap Base Power"],
      ["grant_attribute", "Grant Attribute"],
    ]),
  },
  {
    id: "cost",
    label: "Cost",
    tags: facetTags("cost", [
      ["don_minus", "DON!! Minus"],
      ["don_rest", "Rest DON!!"],
      ["variable_don_return", "Variable DON!! Return"],
      ["rest_self", "Rest Self"],
      ["trash_self", "Trash Self"],
      ["trash_from_hand", "Trash from Hand"],
      [
        "trash_named_card_from_hand_or_stage",
        "Trash Named Card from Hand or Stage",
      ],
      ["trash_from_life", "Trash from Life"],
      ["place_hand_to_deck", "Place Hand to Deck"],
      ["reveal_from_hand", "Reveal from Hand"],
      ["play_named_card_from_hand", "Play Named Card from Hand"],
      ["rest_cards", "Rest Cards"],
      ["rest_named_card", "Rest Named Card"],
      ["ko_own_character", "K.O. Own Character"],
      ["trash_own_character", "Trash Own Character"],
      ["return_own_character_to_hand", "Return Own Character to Hand"],
      ["place_own_character_to_deck", "Place Own Character to Deck"],
      ["place_self_to_deck", "Place Self to Deck"],
      ["place_stage_to_deck", "Place Stage to Deck"],
      ["add_own_character_to_life", "Add Own Character to Life"],
      ["trash_own_stage", "Trash Own Stage"],
      ["place_from_trash_to_deck", "Place from Trash to Deck"],
      ["leader_power_reduction", "Leader Power Reduction"],
      ["give_opponent_don", "Give Opponent DON!!"],
      ["return_attached_don_to_cost", "Return Attached DON!! to Cost Area"],
      ["place_self_and_hand_to_deck", "Place Self and Hand to Deck"],
      ["place_self_and_trash_to_deck", "Place Self and Trash to Deck"],
      ["life_to_hand", "Life to Hand"],
      ["rest_don", "Rest DON!!"],
      ["turn_life_face_up", "Turn Life Face Up"],
      ["turn_life_face_down", "Turn Life Face Down"],
      ["choose_one_cost", "Choose One Cost"],
      ["none", "No Cost"],
    ]),
  },
  {
    id: "condition",
    label: "Condition",
    tags: facetTags("condition", [
      ["life_count", "Life Count"],
      ["character_total_cost", "Character Total Cost"],
      ["hand_count", "Hand Count"],
      ["trash_count", "Trash Count"],
      ["deck_count", "Deck Count"],
      ["don_field_count", "DON!! Field Count"],
      ["active_don_count", "Active DON!! Count"],
      ["all_don_state", "All DON!! State"],
      ["card_on_field", "Card on Field"],
      ["multiple_named_cards", "Multiple Named Cards"],
      ["named_card_with_property", "Named Card with Property"],
      ["field_purity", "Field Purity"],
      ["leader_property", "Leader Property"],
      ["self_power", "Self Power"],
      ["self_cost", "Self Cost"],
      ["self_state", "Self State"],
      ["no_base_effect", "No Base Effect"],
      ["has_effect_type", "Has Effect Type"],
      ["lacks_effect_type", "Lacks Effect Type"],
      ["comparative", "Comparative"],
      ["combined_total", "Combined Total"],
      ["was_played_this_turn", "Was Played This Turn"],
      ["action_performed_this_turn", "Action Performed This Turn"],
      ["play_method", "Play Method"],
      ["face_up_life", "Face-up Life"],
      ["card_type_in_zone", "Card Type in Zone"],
      ["combined_zone_count", "Combined Zone Count"],
      ["board_wide_existence", "Board-wide Existence"],
      ["rested_card_count", "Rested Card Count"],
      ["don_given", "DON!! Given"],
      ["turn_count", "Turn Count"],
      ["is_my_turn", "Is My Turn"],
      ["source_property", "Source Property"],
      ["revealed_card_property", "Revealed Card Property"],
    ]),
  },
  {
    id: "flag",
    label: "Flag",
    tags: facetTags("flag", [
      ["once_per_turn", "Once per Turn"],
      ["optional", "Optional"],
      ["lock_on_decline", "Lock on Decline"],
    ]),
  },
] as const;

export type EffectFacetTag =
  (typeof EFFECT_FACET_GROUPS)[number]["tags"][number]["id"];
