import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { parseEffectLine, type EffectSegment } from "./effect-notation";

/**
 * The cost grammar against every card the repository has text for.
 *
 * `parseEffectLine` decides which phrase before a colon is the price of an
 * effect. That decision is only as good as the shapes it was measured on, so
 * this reads the committed corpus (`docs/cards/`, generated by
 * `scripts/generate-card-docs.ts` — the vegapull source JSON is not in the
 * repository) and holds the grammar to both halves of the bargain:
 *
 * - **Recall** — nearly every colon a card prints outside its notation is a
 *   cost, so the priced share of colon-bearing lines is asserted from below.
 * - **Precision** — the lines it declines to price are enumerated exactly. That
 *   is the load-bearing half: emphasizing a run of ordinary prose misreads the
 *   card, so every unpriced colon line is listed and reviewed below, and a
 *   colon shape this list does not name fails here rather than quietly picking
 *   up bold on a page.
 */

const CORPUS_DIR = fileURLToPath(new URL("../../../docs/cards", import.meta.url));

/**
 * One printed effect per entry. The corpus interleaves effect text with Markdown
 * chrome — a set heading, a card-name heading, a bold metadata line, and a rule
 * between cards — and nothing else in the file is card text. `<br>` is
 * normalized first because that is what the source data uses for an effect
 * break; today's generator already writes newlines, and normalizing keeps this
 * reading effects rather than joined-up pairs if that ever changes.
 */
function readCorpusEffectLines(): string[] {
  const lines: string[] = [];

  for (const entry of readdirSync(CORPUS_DIR)) {
    if (!entry.endsWith(".md")) continue;

    const source = readFileSync(join(CORPUS_DIR, entry), "utf8").replace(
      /<br\s*\/?>/gi,
      "\n"
    );

    for (const raw of source.split(/\r?\n/)) {
      const line = raw.trim();
      if (line.length === 0) continue;
      if (line.startsWith("#")) continue;
      if (line.startsWith("---")) continue;
      if (line.startsWith("**")) continue;
      lines.push(line);
    }
  }

  return [...new Set(lines)];
}

/** Printed text of a segment tree, delimiters restored. */
function printed(segments: EffectSegment[]): string {
  return segments
    .map((segment) => {
      switch (segment.kind) {
        case "text":
          return segment.text;
        case "notation":
          return `[${segment.label}]`;
        case "trait":
          return `{${segment.label}}`;
        case "cost":
          return printed(segment.segments);
      }
    })
    .join("");
}

function costsOf(line: string): string[] {
  return parseEffectLine(line).flatMap((segment) =>
    segment.kind === "cost" ? [printed(segment.segments)] : []
  );
}

/**
 * A colon that is not inside notation, a trait, or reminder text — the only kind
 * a cost can end on. Read here independently of the parser so that a bug in the
 * parser's own scan cannot hide by shrinking the population it is measured
 * against.
 */
function hasTopLevelColon(line: string): boolean {
  let depth = 0;

  for (const character of line) {
    if ("[{(".includes(character)) depth += 1;
    else if ("]})".includes(character)) depth = Math.max(0, depth - 1);
    else if (character === ":" && depth === 0) return true;
  }

  return false;
}

/** The phrase a line offers as its price, before the parser judges it. */
function precolonPhrase(line: string): string {
  const body = line.replace(/^(?:\s*\[[^\]]*\]\s*\/?\s*)*/, "");
  const colon = body.indexOf(":");
  return (colon === -1 ? body : body.slice(0, colon)).trim();
}

/**
 * Every colon-bearing line in the corpus the grammar declines to price, by the
 * phrase it declines. Each entry is a reviewed judgment about a real card, not a
 * regression baseline — adding one asserts "this phrase is not a price".
 *
 * The first nine are option headers: prose that introduces a list of modes, not
 * something the player pays. They are the reason the grammar insists on a
 * payment marker instead of taking any pre-colon phrase.
 *
 * The last three are the grammar's known misses, kept here so they stay visible:
 *
 * - Two printed costs are written as a bare imperative. A bare imperative is
 *   indistinguishable from the sentence of an effect body except by knowing
 *   which verbs name payments, and `Choose one:` and `Apply each of the
 *   following effects…:` are bare imperatives too — so pricing them would take a
 *   verb allowlist, which would be a guess about sets this corpus does not
 *   contain.
 * - One card's two effects run together in the source with no break between the
 *   first effect's full stop and the second's `[On Your Opponent's Attack]`
 *   heading. The second effect really does have a cost, but pricing it would
 *   mean emphasizing from the top of a sentence that already ended.
 */
const UNPRICED_COLON_PHRASES = [
  "Choose one",
  "Your opponent chooses one",
  "Draw 1 card, then choose one",
  "Apply each of the following effects based on the number of cards in your trash",
  "If the number of DON!! cards on your field is equal to or less than the number on your opponent's field, choose one",
  "If your Leader is [Lucy], choose one",
  "If your Leader is [Uta], choose one",
  "If your Leader is multicolored, choose one",
  "If your opponent has 5 or more cards in their hand, choose one",
  "Rest 1 of your DON!! cards and you may rest this Character",
  "Place 1 of your opponent's Characters with a cost of 3 or less at the top or bottom of your opponent's Life cards face-up",
  "Give up to 1 rested DON!! card to your Leader or 1 of your Characters.[On Your Opponent's Attack] [Once Per Turn] You may trash 1 card from your hand",
];

describe("cost grammar against the printed corpus", () => {
  const effectLines = readCorpusEffectLines();
  const colonLines = effectLines.filter(hasTopLevelColon);
  const priced = colonLines.filter((line) => costsOf(line).length > 0);
  const unpriced = colonLines.filter((line) => costsOf(line).length === 0);

  it("reads a non-trivial corpus", () => {
    // Floors, not fixtures: a new set adds cards and must not fail this.
    expect(effectLines.length).toBeGreaterThanOrEqual(2400);
    expect(colonLines.length).toBeGreaterThanOrEqual(750);
  });

  it("prices nearly every colon a card prints outside its notation", () => {
    expect(priced.length).toBeGreaterThanOrEqual(740);
    expect(priced.length / colonLines.length).toBeGreaterThanOrEqual(0.97);
  });

  it("declines exactly the reviewed set of colon phrases", () => {
    const declined = [...new Set(unpriced.map(precolonPhrase))].sort();

    expect(declined).toEqual([...UNPRICED_COLON_PHRASES].sort());
  });

  it("keeps every reviewed exclusion unpriced on the card that prints it", () => {
    for (const phrase of UNPRICED_COLON_PHRASES) {
      const printing = colonLines.filter(
        (line) => precolonPhrase(line) === phrase
      );

      expect(printing.length).toBeGreaterThan(0);
      for (const line of printing) expect(costsOf(line)).toEqual([]);
    }
  });

  it("prices one clause and never the colon or what follows it", () => {
    for (const line of priced) {
      for (const cost of costsOf(line)) {
        expect(cost).not.toBe("");
        expect(cost).toBe(cost.trim());
        expect(cost).not.toContain(":");
        expect(cost).not.toContain(";");
      }
    }
  });

  it("opens every priced cost on a printed payment marker", () => {
    const openers = /^(?:DON!!\s*−\s*\d+|[①-⑳➀-➓]|[Yy]ou\s+(?:may|can)\s)/;

    for (const line of priced) {
      const [first] = costsOf(line);
      expect(first).toMatch(openers);
    }
  });

  it("carries every line through unchanged whatever it prices", () => {
    for (const line of effectLines) {
      expect(printed(parseEffectLine(line))).toBe(line);
    }
  });
});
